apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: chase_travel_clone-booking-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: wayfarer-common-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/bookingdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            failureThreshold: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - port: 8085
      targetPort: 8085
